#!/usr/bin/env npx tsx
/**
 * Full pipeline: Postman Collection → Split by Auth → OpenAPI → TypeScript Types
 *
 * Schema source: https://www.postman.com/fatsecret/fatsecret-public-apis/
 * Usage: npm run generate
 */

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

function run(cmd: string) {
  console.log(`> ${cmd}`);
  execSync(cmd, { cwd: ROOT, stdio: 'inherit' });
}

// Step 1: Split Postman collection by auth type
console.log('\n📦 Step 1: Splitting Postman collection by auth type...');
run('npx tsx scripts/split-collection.ts');

// Step 2: Convert to OpenAPI
console.log('\n📋 Step 2: Converting to OpenAPI...');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const p2o = require('postman-to-openapi');
await p2o(join(ROOT, 'schemas/public-api.postman.json'), join(ROOT, 'schemas/public-api.yaml'));
await p2o(join(ROOT, 'schemas/profile-api.postman.json'), join(ROOT, 'schemas/profile-api.yaml'));
console.log('✅ OpenAPI schemas generated');

// Step 3: Fix base URLs (Postman variables → actual URLs)
console.log('\n🔧 Step 3: Fixing base URLs...');
for (const file of ['schemas/public-api.yaml', 'schemas/profile-api.yaml']) {
  const path = join(ROOT, file);
  let content = readFileSync(path, 'utf-8');
  content = content.replace(/url: undefined:\/\/\{\{base_url_path\}\}/g, 'url: https://platform.fatsecret.com/rest');
  content = content.replace(/url: undefined:\/\/\{\{oauth1_url\}\}/g, 'url: https://authentication.fatsecret.com/oauth');
  writeFileSync(path, content);
}
console.log('✅ Base URLs fixed');

// Step 4: Generate TypeScript types (openapi-typescript → .d.ts)
console.log('\n🔨 Step 4: Generating TypeScript types...');
run('npx openapi-typescript schemas/public-api.yaml -o src/generated/public-api.d.ts');
run('npx openapi-typescript schemas/profile-api.yaml -o src/generated/profile-api.d.ts');

// Step 5: Generate Zod schemas from OpenAPI
console.log('\n🔨 Step 5: Generating Zod schemas...');
run('npx typed-openapi schemas/public-api.yaml -o src/generated/public-api.zod.ts -r zod');
run('npx typed-openapi schemas/profile-api.yaml -o src/generated/profile-api.zod.ts -r zod');

// Strip utility types (ApiClient, EndpointByMethod etc.) — they have Zod version compat issues
for (const file of ['src/generated/public-api.zod.ts', 'src/generated/profile-api.zod.ts']) {
  const path = join(ROOT, file);
  let content = readFileSync(path, 'utf-8');
  const marker = '// <EndpointByMethod>';
  const idx = content.indexOf(marker);
  if (idx !== -1) {
    content = content.substring(0, idx);
    writeFileSync(path, content);
  }
}
console.log('✅ Zod schemas generated');

// Step 6: Add generation banner with source and date
console.log('\n📝 Step 6: Adding generation banner...');
const generatedAt = new Date().toISOString().split('T')[0];
const banner = (name: string) =>
  `/**\n` +
  ` * ${name}\n` +
  ` *\n` +
  ` * Auto-generated from FatSecret Postman collection.\n` +
  ` * Source: https://www.postman.com/fatsecret/fatsecret-public-apis/\n` +
  ` * Generated: ${generatedAt}\n` +
  ` *\n` +
  ` * Do not edit manually — run \`npm run generate\` to regenerate.\n` +
  ` */\n`;

for (const [file, name] of [
  ['src/generated/public-api.d.ts', 'FatSecret Public API (OAuth 2.0)'],
  ['src/generated/profile-api.d.ts', 'FatSecret Profile API (3-Legged OAuth 1.0)'],
] as const) {
  const path = join(ROOT, file);
  let content = readFileSync(path, 'utf-8');
  // Replace the default openapi-typescript banner
  content = content.replace(
    /\/\*\*\n \* This file was auto-generated by openapi-typescript\.\n \* Do not make direct changes to the file\.\n \*\//,
    banner(name).trim(),
  );
  writeFileSync(path, content);
}
console.log('✅ Banners added');

console.log('\n✅ Done! Generated:');
console.log('  - src/generated/public-api.d.ts  (OAuth 2.0 - food search, recipes, brands)');
console.log('  - src/generated/profile-api.d.ts (3-Legged OAuth 1.0 - food diary, weight, exercises)');
